
insert into drivers (driver_id, name, car_model, status) values (1, 'Vassily Kornilyev', 'Classic', 'available');
insert into drivers (driver_id, name, car_model, status) values (2, 'Cherin Kenforth', 'SRX', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (3, 'Lenore Duffield', 'Legend', 'available');
insert into drivers (driver_id, name, car_model, status) values (4, 'Ki Comini', 'Esteem', 'available');
insert into drivers (driver_id, name, car_model, status) values (5, 'Doria Cholerton', '57', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (6, 'Rozelle Handrick', 'Grand Marquis', 'available');
insert into drivers (driver_id, name, car_model, status) values (7, 'Jonathon Dybbe', 'Intrepid', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (8, 'Mercedes Ginnell', 'Silverado 1500', 'available');
insert into drivers (driver_id, name, car_model, status) values (9, 'Lyn Torrie', 'Ram', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (10, 'Karoly Farlambe', 'S60', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (11, 'Andre Gallamore', 'Tiburon', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (12, 'Tobe Stille', 'Colt', 'available');
insert into drivers (driver_id, name, car_model, status) values (13, 'Valida Webben', 'SLK-Class', 'available');
insert into drivers (driver_id, name, car_model, status) values (14, 'Samson De Carolis', 'RL', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (15, 'Basilius Peyntue', 'Prius', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (16, 'Debera Gisbey', '323', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (17, 'Elysha Casterot', 'Civic', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (18, 'Dorthy Tinan', 'Eclipse', 'available');
insert into drivers (driver_id, name, car_model, status) values (19, 'Ferris Marmyon', 'Murciélago', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (20, 'Terrie Eyree', 'Forester', 'available');
insert into drivers (driver_id, name, car_model, status) values (21, 'Jana Hakking', '924 S', 'available');
insert into drivers (driver_id, name, car_model, status) values (22, 'Nadya Mattiato', 'Vandura 3500', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (23, 'Dyann Burdytt', 'Grand Caravan', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (24, 'Eugene Goalby', 'Malibu', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (25, 'Feodora Thring', 'Dynasty', 'available');
insert into drivers (driver_id, name, car_model, status) values (26, 'Quincy Hallgath', 'Eclipse', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (27, 'Hewie Caselli', 'B-Series', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (28, 'Kyla Cornall', 'Metro', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (29, 'Fowler Woodnutt', 'Ram 2500 Club', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (30, 'Kahaleel McAllister', 'Impala', 'available');
insert into drivers (driver_id, name, car_model, status) values (31, 'Page Dobbyn', 'Familia', 'available');
insert into drivers (driver_id, name, car_model, status) values (32, 'Morley Cluelow', 'Pajero', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (33, 'Romonda Kirtley', 'Forester', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (34, 'Alyda Balcock', 'Fiero', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (35, 'Willem Bowden', 'RX-7', 'available');
insert into drivers (driver_id, name, car_model, status) values (36, 'Kin Pearson', 'Outback', 'available');
insert into drivers (driver_id, name, car_model, status) values (37, 'Aviva Loughren', 'Civic', 'available');
insert into drivers (driver_id, name, car_model, status) values (38, 'Jammie Baxter', 'Grand Prix', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (39, 'Ebony Harpin', 'Xterra', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (40, 'Rand Frankcom', 'G-Class', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (41, 'Lilias Buckles', 'Firefly', 'available');
insert into drivers (driver_id, name, car_model, status) values (42, 'Kristoffer Booker', 'B-Series', 'available');
insert into drivers (driver_id, name, car_model, status) values (43, 'Blair Nixon', 'SC', 'available');
insert into drivers (driver_id, name, car_model, status) values (44, 'Lennard Hellcat', 'Sierra 1500', 'available');
insert into drivers (driver_id, name, car_model, status) values (45, 'Giuditta Bucklan', 'Sprinter', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (46, 'Gardie Leibold', 'F250', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (47, 'Janette Gerge', 'Freestar', 'available');
insert into drivers (driver_id, name, car_model, status) values (48, 'Giordano Rollins', 'I', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (49, 'Sherye Hubert', 'B-Series', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (50, 'Meridith Riddett', 'Mustang', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (51, 'Eada Shurmer', 'Dakota Club', 'available');
insert into drivers (driver_id, name, car_model, status) values (52, 'Truman Chester', 'Astro', 'available');
insert into drivers (driver_id, name, car_model, status) values (53, 'Joseph Claiden', '745', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (54, 'Alleen Pover', 'Pathfinder', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (55, 'Inigo Mazzeo', 'Grand Prix', 'available');
insert into drivers (driver_id, name, car_model, status) values (56, 'Johny Hanbury-Brown', 'Mazdaspeed 3', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (57, 'Kalinda Sisey', 'Thunderbird', 'available');
insert into drivers (driver_id, name, car_model, status) values (58, 'Stephani Cromb', 'Viper', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (59, 'Carry Hallwell', 'MKZ', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (60, 'Gunar Banat', 'MX-5', 'available');
insert into drivers (driver_id, name, car_model, status) values (61, 'Lazarus Mabley', 'Arnage', 'available');
insert into drivers (driver_id, name, car_model, status) values (62, 'Amil Rodden', 'Accent', 'available');
insert into drivers (driver_id, name, car_model, status) values (63, 'Sanderson Waymont', '98', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (64, 'Briney Elsmere', 'Ram', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (65, 'Evey Plaice', 'Jetta', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (66, 'Ashby Lansberry', 'Tracer', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (67, 'Minor Ledeker', 'LeMans', 'available');
insert into drivers (driver_id, name, car_model, status) values (68, 'Aristotle Lange', 'Sunbird', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (69, 'Cad Wethered', 'H1', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (70, 'Dari Croose', '2500', 'available');
insert into drivers (driver_id, name, car_model, status) values (71, 'Hakeem Godier', 'Taurus', 'available');
insert into drivers (driver_id, name, car_model, status) values (72, 'Bond Ethridge', 'Windstar', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (73, 'Noak Thynn', 'Accord', 'available');
insert into drivers (driver_id, name, car_model, status) values (74, 'Gib Brittain', 'Camry', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (75, 'Calvin Rowlings', 'Pathfinder', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (76, 'Dede Millsom', 'GTO', 'available');
insert into drivers (driver_id, name, car_model, status) values (77, 'Noni Mixture', 'Voyager', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (78, 'Larine Broomhall', 'SL-Class', 'available');
insert into drivers (driver_id, name, car_model, status) values (79, 'Lin Paley', 'Monte Carlo', 'available');
insert into drivers (driver_id, name, car_model, status) values (80, 'Casar Marvell', 'Mustang', 'available');
insert into drivers (driver_id, name, car_model, status) values (81, 'Darlene Dadswell', 'Grand Prix', 'available');
insert into drivers (driver_id, name, car_model, status) values (82, 'Gino Deerr', 'Seville', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (83, 'Corene Becker', 'Canyon', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (84, 'Lani Mildner', 'TL', 'available');
insert into drivers (driver_id, name, car_model, status) values (85, 'Deny Joynson', 'E250', 'available');
insert into drivers (driver_id, name, car_model, status) values (86, 'Roseline Povall', 'B-Series Plus', 'available');
insert into drivers (driver_id, name, car_model, status) values (87, 'Linda Hacker', 'Altima', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (88, 'Nicole Yitzhakov', 'SLS AMG', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (89, 'Cassi Camois', 'Cirrus', 'available');
insert into drivers (driver_id, name, car_model, status) values (90, 'Glenn Fidoe', 'Aviator', 'available');
insert into drivers (driver_id, name, car_model, status) values (91, 'Inna McSweeney', 'Bravada', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (92, 'Clara Schaben', '57', 'available');
insert into drivers (driver_id, name, car_model, status) values (93, 'Clair Lovelock', 'Veyron', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (94, 'Benton Giral', 'Previa', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (95, 'Marita Iacovacci', 'Mariner', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (96, 'Brantley Flukes', 'Expedition', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (97, 'Sergio Gavan', 'Econoline E150', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (98, 'Harbert Beaulieu', 'Sunfire', 'available');
insert into drivers (driver_id, name, car_model, status) values (99, 'Josias Thornthwaite', 'Millenia', 'on_trip');
insert into drivers (driver_id, name, car_model, status) values (100, 'Melessa Piperley', '3500', 'available');
